name: clothes_shop
description: Modern E-commerce Clothes Store
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.2
  
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  
  # State Management
  provider: ^6.1.1
  
  # API & Networking
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Navigation
  go_router: ^13.0.0
  
  # Utils
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  image_picker: ^1.0.5
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  
  # Payment (optional)
  flutter_stripe: ^9.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700