# Generated by Django 5.0.1 on 2025-08-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['color_name']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['size__size_name', 'color__color_name']},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['size_name']},
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs'),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(blank=True, help_text='Hex color code (e.g., #FF0000)', max_length=7, null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='color',
            table='colors',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table='product_variants',
        ),
        migrations.AlterModelTable(
            name='size',
            table='sizes',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
